import { createRequire } from 'node:module';
import { mkdirSync, statSync } from 'node:fs';
const sharp = createRequire(import.meta.url)('sharp');

const ROOT = '/Users/mangejlu/Documents/Claude';
mkdirSync('public/media', { recursive: true });

/**
 * Everything ships as WebP at two widths for a srcset. HEIC in particular has
 * to be converted: Safari renders it, nothing else does, so shipping it as-is
 * would leave most visitors with a broken image.
 */
const JOBS = [
  // HAWK product screenshots — tall app captures.
  ['Case Study Images/Hawk/DashboardHawk.png',        'hawk-dashboard'],
  ['Case Study Images/Hawk/FindingsProcessHawk.png',  'hawk-findings'],
  ['Case Study Images/Hawk/WorkspaceHawk.png',        'hawk-workspace'],
  ['Case Study Images/Hawk/AskDocumentation.png',     'hawk-request'],
  // Hobbies.
  ['Hobbies/ArtPainting/91B0DDD8-C57D-429D-A4EC-166279CF998D.JPG', 'about-painting-1'],
  ['Hobbies/ArtPainting/A15A27C6-5065-49DE-9B3E-95FD768B493E.JPG', 'about-painting-2'],
  ['Hobbies/Art, theatre/IMG_0647.jpg',                            'about-theatre'],
];

/**
 * HEIC goes through macOS `sips` first: sharp's HEIF decoder fails on Apple's
 * variant ("bad seek"), and HEIC only renders in Safari anyway, so these have
 * to become WebP regardless.
 */
const STAGE = '/private/tmp/claude-501/-Users-mangejlu-Documents-Claude/a1e6fee3-8cef-43de-a61f-56b93324a3bc/scratchpad/heic';
const HEIC_JOBS = [
  [`${STAGE}/IMG_5591.jpg`, 'about-nobel'],
  [`${STAGE}/IMG_1616.jpg`, 'about-travel-1'],
  [`${STAGE}/IMG_2048.jpg`, 'about-travel-2'],
  [`${STAGE}/IMG_2419.jpg`, 'about-travel-3'],
];

const WIDTHS = [800, 1600];
let total = 0;

/**
 * Records the width each variant was actually written at.
 *
 * Sources narrower than 1600px can't produce a real 1600px file without
 * upscaling, and advertising one in a srcset that doesn't exist gives every
 * high-DPI visitor a broken image. So the manifest carries true widths and the
 * components build their srcset from it.
 */
const manifest = {};

const ALL = [
  ...JOBS.map(([rel, name]) => [`${ROOT}/${rel}`, name]),
  ...HEIC_JOBS,
];

for (const [src, name] of ALL) {
  const meta = await sharp(src).metadata();
  const variants = [];
  for (const w of WIDTHS) {
    const out = `public/media/${name}-${w}.webp`;
    const info = await sharp(src)
      .rotate()                       // honour EXIF orientation
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 78 })
      .toFile(out);
    // withoutEnlargement means the file can come out narrower than asked.
    variants.push({ file: `${name}-${w}.webp`, width: info.width, height: info.height });
    total += statSync(out).size;
  }
  // Drop a variant that ended up identical in width to a smaller one.
  const unique = [];
  for (const v of variants) {
    if (!unique.some((u) => u.width === v.width)) unique.push(v);
  }
  manifest[name] = { variants: unique, width: unique.at(-1).width, height: unique.at(-1).height };
  const first = statSync(`public/media/${name}-${WIDTHS[0]}.webp`);
  console.log(
    `${name.padEnd(20)} ${String(meta.width) + 'x' + meta.height}`.padEnd(38) +
    `-> ${(statSync(src).size / 1024 / 1024).toFixed(2)}MB becomes ${(first.size / 1024).toFixed(0)}KB @800w`,
  );
}
console.log(`\ntotal image payload: ${(total / 1024 / 1024).toFixed(2)} MB`);

const { writeFileSync } = await import('node:fs');
writeFileSync(
  'src/data/media.ts',
  '// Generated by scripts/convert-images.mjs. Do not edit by hand.\n' +
  '// Carries the width each variant was really written at, so srcset never\n' +
  '// advertises a file that was skipped as an upscale.\n' +
  'export const media = ' + JSON.stringify(manifest, null, 2) + ' as const;\n' +
  '\nexport type MediaName = keyof typeof media;\n',
);
console.log('wrote src/data/media.ts');
