// Generated by scripts/convert-images.mjs. Do not edit by hand.
// Carries the width each variant was really written at, so srcset never
// advertises a file that was skipped as an upscale.
export const media = {
  "hawk-dashboard": {
    "variants": [
      {
        "file": "hawk-dashboard-800.webp",
        "width": 800,
        "height": 410
      },
      {
        "file": "hawk-dashboard-1600.webp",
        "width": 1600,
        "height": 821
      }
    ],
    "width": 1600,
    "height": 821
  },
  "hawk-findings": {
    "variants": [
      {
        "file": "hawk-findings-800.webp",
        "width": 800,
        "height": 410
      },
      {
        "file": "hawk-findings-1600.webp",
        "width": 1600,
        "height": 821
      }
    ],
    "width": 1600,
    "height": 821
  },
  "hawk-workspace": {
    "variants": [
      {
        "file": "hawk-workspace-800.webp",
        "width": 800,
        "height": 410
      },
      {
        "file": "hawk-workspace-1600.webp",
        "width": 1600,
        "height": 821
      }
    ],
    "width": 1600,
    "height": 821
  },
  "hawk-request": {
    "variants": [
      {
        "file": "hawk-request-800.webp",
        "width": 800,
        "height": 410
      },
      {
        "file": "hawk-request-1600.webp",
        "width": 1600,
        "height": 821
      }
    ],
    "width": 1600,
    "height": 821
  },
  "bloom-map": {
    "variants": [
      {
        "file": "bloom-map-800.webp",
        "width": 640,
        "height": 339
      }
    ],
    "width": 640,
    "height": 339
  },
  "bloom-alerts": {
    "variants": [
      {
        "file": "bloom-alerts-800.webp",
        "width": 640,
        "height": 339
      }
    ],
    "width": 640,
    "height": 339
  },
  "about-painting-1": {
    "variants": [
      {
        "file": "about-painting-1-800.webp",
        "width": 800,
        "height": 1422
      },
      {
        "file": "about-painting-1-1600.webp",
        "width": 1170,
        "height": 2080
      }
    ],
    "width": 1170,
    "height": 2080
  },
  "about-painting-2": {
    "variants": [
      {
        "file": "about-painting-2-800.webp",
        "width": 800,
        "height": 1422
      },
      {
        "file": "about-painting-2-1600.webp",
        "width": 1170,
        "height": 2080
      }
    ],
    "width": 1170,
    "height": 2080
  },
  "about-theatre": {
    "variants": [
      {
        "file": "about-theatre-800.webp",
        "width": 800,
        "height": 431
      },
      {
        "file": "about-theatre-1600.webp",
        "width": 1600,
        "height": 861
      }
    ],
    "width": 1600,
    "height": 861
  },
  "kairuu-documents": {
    "variants": [
      {
        "file": "kairuu-documents-800.webp",
        "width": 800,
        "height": 454
      },
      {
        "file": "kairuu-documents-1600.webp",
        "width": 1600,
        "height": 907
      }
    ],
    "width": 1600,
    "height": 907
  },
  "kairuu-upload": {
    "variants": [
      {
        "file": "kairuu-upload-800.webp",
        "width": 800,
        "height": 454
      },
      {
        "file": "kairuu-upload-1600.webp",
        "width": 1600,
        "height": 907
      }
    ],
    "width": 1600,
    "height": 907
  },
  "kairuu-resource": {
    "variants": [
      {
        "file": "kairuu-resource-800.webp",
        "width": 800,
        "height": 454
      },
      {
        "file": "kairuu-resource-1600.webp",
        "width": 1600,
        "height": 907
      }
    ],
    "width": 1600,
    "height": 907
  },
  "kairuu-library": {
    "variants": [
      {
        "file": "kairuu-library-800.webp",
        "width": 800,
        "height": 454
      },
      {
        "file": "kairuu-library-1600.webp",
        "width": 1600,
        "height": 907
      }
    ],
    "width": 1600,
    "height": 907
  },
  "about-nobel": {
    "variants": [
      {
        "file": "about-nobel-800.webp",
        "width": 800,
        "height": 1067
      },
      {
        "file": "about-nobel-1600.webp",
        "width": 1600,
        "height": 2133
      }
    ],
    "width": 1600,
    "height": 2133
  },
  "about-travel-1": {
    "variants": [
      {
        "file": "about-travel-1-800.webp",
        "width": 800,
        "height": 1067
      },
      {
        "file": "about-travel-1-1600.webp",
        "width": 1600,
        "height": 2133
      }
    ],
    "width": 1600,
    "height": 2133
  },
  "about-travel-2": {
    "variants": [
      {
        "file": "about-travel-2-800.webp",
        "width": 800,
        "height": 1067
      },
      {
        "file": "about-travel-2-1600.webp",
        "width": 1600,
        "height": 2133
      }
    ],
    "width": 1600,
    "height": 2133
  },
  "about-travel-3": {
    "variants": [
      {
        "file": "about-travel-3-800.webp",
        "width": 800,
        "height": 1067
      },
      {
        "file": "about-travel-3-1600.webp",
        "width": 1600,
        "height": 2133
      }
    ],
    "width": 1600,
    "height": 2133
  }
} as const;

export type MediaName = keyof typeof media;
